#### 넘파이(numpy)
- pandas, 머신러닝 라이브러리에서 기본적으로 필요한 라이브러리
- 파이썬 list 보다 빠름 / 메모리는 적게 사용
- 빌트인 함수 : 선형대수, 통계 관련 여러 함수 내장
- 데이터 구조
    - ndarray

In [1]:
import numpy as np

In [ ]:
# 1차원 백터 생성
array1 = np.array([1,2,3])
array1 #array([1, 2, 3])

array([1, 2, 3])

In [ ]:
print(type(array1)) # numpy.ndarray
print(array1.shape) #(3,)

<class 'numpy.ndarray'>
(3,)


In [ ]:
# 2 차원 백터 생성
array2 = np.array([[1,2,3],[4,5,6]])
print(array2)
print(array2.shape) # (2,3)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
# 파이썬 리스트
list1 = [1,2,'a','b',True]
list1

[1, 2, 'a', 'b', True]

In [ ]:
array1.dtype # int64


dtype('int64')

In [ ]:
array3 = np.array([1,2,3.1])
print(array3.dtype) # float64 -> 큰수에 맞춰줌

float64


In [13]:
array4 = np.array(list1)
print(array4.dtype)

<U21


In [ ]:
# ndarray 다양한 방법으로 생성하기

In [ ]:
np.arange(10)
np.arange(5,10)
np.arange(1,10,2) # range와 유사한 개념

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros(5) # 0.~~ 으로 만듬 그게 싫으면
np.zeros(5,dtype="int32") # array([0, 0, 0, 0, 0], dtype=int32)

array([0, 0, 0, 0, 0], dtype=int32)

In [ ]:
np.ones(5,dtype="int32") # 1로 채우기

array([1, 1, 1, 1, 1], dtype=int32)

In [19]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [20]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
np.eye(5) # 처음과 끝을 대각선으로 이으며 1, 나머지는 0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(1,10,5) #array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
array1.reshape(2,5)
#array([[0, 1, 2, 3, 4],
    #    [5, 6, 7, 8, 9]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
array1.reshape(-1,5) # -1: 알아서 해라
array1.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
# 임의의 수로 ndarray 생성
np.random.rand(2,3)

array([[0.64665663, 0.68205504, 0.76385874],
       [0.37004854, 0.98016669, 0.08320166]])

In [28]:
# 정규분포
np.random.randn(2,3)

array([[ 0.76950542, -1.62885957, -1.20342433],
       [-1.00342803,  1.48989494, -1.53662766]])

In [30]:
# 1~10 사이의 임의의 수
np.random.randint(1,10,5)
np.random.randint(1,100,(5,4))

array([[83, 10, 66, 34],
       [68, 44, 44, 61],
       [26, 20, 46,  5],
       [46, 19, 67, 67],
       [49, 19, 59, 80]], dtype=int32)

In [32]:
np.random.seed(42) # 숫자는 아무거나 상관없이 결과값 동일하게 출력
np.random.randn(3,4)

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

In [36]:
# 인덱싱, 슬라이싱
array1 = np.arange(1,10)
array1[-1]
array1[:3]


array([1, 2, 3])

In [37]:
array2 = array1.reshape(3,3)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2[[0,1],2]

array([3, 6])

In [ ]:
list1 = list(range(10))
list1
# list1[list1>5] 파이썬 리스트는 불가능


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
# 행렬 사칙연산
x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])

In [42]:
print(x+y)
print(x-y)
print(x*y)
print(x//y)

[[ 5  5  5]
 [10 10 10]]
[[3 3 3]
 [6 6 6]]
[[ 4  4  4]
 [16 16 16]]
[[4 4 4]
 [4 4 4]]


In [43]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8],[9,10],[11,12]])

In [44]:
print(np.dot(x,y))

[[ 58  64]
 [139 154]]


In [45]:
# 전치행렬
np.transpose(x)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
v = np.array([3,4])

# norm(ord=Norm 의 종류)
# L1(Manhattan distance), L2(Euclidean distance), Max(절대값 중 가장 큰 값)


np.linalg.norm(v)

np.float64(5.0)